### PR TITLE
Add Pirate Realm to relay

### PR DESCRIPTION
**Pull request by Phate4569**
Edit to add pirate realm to relay.

### CODE REVIEW

**Comment by soolar** [comment]
Can you also run BUILD/assemble.sh? (From in the BUILD directory). If not, I can after I approve the merge, which is fine too.

**Comment by Phate4569** [comment]
I can't right now, I'm on mobile.

**Comment by jaspercb** [comment]
Don't entries need to be tab-separated? Plus the assemble.sh line. Please test your code.

**Comment by Phate4569** [comment]
WTF. Everything I edit on Git's GUI editor gets changed to spaces rather than tab?! See my latest commit where I deleted and reinserted the tabs on frAlways.

I am unfamiliar with github, I only really use my company's internal git.

**Comment by Phate4569** [comment]
Please just delete this pull (I am trying to figure out how to do it and failing miserably).

**Comment by soolar** [comment]
You can't delete a pull request, but you can close it.

**Comment by soolar** [comment]
I've gone ahead and done this myself since it's a simple fix. Thanks for bringing it to my attention!

**Pull request closed without merging**
