### PR TITLE
Improve check for finished war, and safer vampyre war selling

### LINKED ISSUE #166: Script bails out of combat with lv 13 boss - can't pick up afterwards
As above, Standard HC run as a DB. Fighting the war until the hippy boss - so far so good. But then struggled in the combat and asked me to take over in the relay browser. I did this and won the combat, started the script again but it can't continue. Looked at the soolascend quest tracker and sl_war is "finished"

Output here:

> Let's fight the boss!
Starting preadventure script...
Pre Adventure at The Battlefield (Frat Uniform) done, beep.
About to start a combat indirectly at The Battlefield (Frat Uniform)... (3) accesses required.

>[808] Frat House
Encounter: The Big Wisniewski
Round 0: eventvwr wins initiative!
Round 1: Polyfella is just skin and bones. Well, slime and slime, technically, but still -- you should feed him!
ccAdvBypass has encountered a combat! (param: 'sl_combatHandler')

>[808] The Battlefield (Frat Uniform)
Encounter: The Big Wisniewski
Round 0: eventvwr loses initiative!
sl_combatHandler: 0
Round 1: eventvwr tries to steal an item!
Round 2: You lose 1 hit point
Round 2: You lose 10 hit points
Round 2: eventvwr casts SING ALONG!
Round 3: You lose 1 hit point
Round 3: You lose 20 hit points
Round 3: eventvwr attacks!
Round 4: The Big Wisniewski takes 4 damage.
Round 4: You lose 1 hit point
Round 4: You lose 19 hit points
Round 4: eventvwr attacks!
Round 5: The Big Wisniewski takes 3 damage.
Round 5: Polyfella lodges the ice-cold pick in your enemy, dealing 20 damage.
Round 5: The Big Wisniewski takes 20 damage.
Round 5: You lose 1 hit point
Round 5: You lose 20 hit points
Round 5: eventvwr attacks!
Round 6: The Big Wisniewski takes 5 damage.
Round 6: Polyfella lodges the ice-cold pick in your enemy, dealing 20 damage.
Round 6: The Big Wisniewski takes 20 damage.
Round 6: You lose 1 hit point
Round 6: You lose 19 hit points
Round 6: eventvwr attacks!
Round 7: The Big Wisniewski takes 3 damage.
Round 7: Polyfella lodges the ice-cold pick in your enemy, dealing 22 damage.
Round 7: The Big Wisniewski takes 22 damage.
Round 7: You lose 1 hit point
Round 7: You lose 20 hit points
Round 7: eventvwr attacks!
Round 8: You lose 3 hit points
Round 8: You lose 1 hit point
Round 8: You lose 18 hit points
Round 8: eventvwr attacks!
Round 9: The Big Wisniewski takes 4 damage.
Round 9: Polyfella lodges the ice-cold pick in your enemy, dealing 24 damage.
Round 9: The Big Wisniewski takes 24 damage.
Round 9: You lose 1 hit point
Round 9: You lose 19 hit points
Round 9: eventvwr attacks!
Round 10: The Big Wisniewski takes 4 damage.
Round 10: Polyfella lodges the ice-cold pick in your enemy, dealing 20 damage.
Round 10: The Big Wisniewski takes 20 damage.
Round 10: You lose 1 hit point
Round 10: eventvwr attacks!
Round 11: The Big Wisniewski takes 3 damage.
Round 11: You lose 1 hit point
Round 11: You lose 18 hit points
Round 11: eventvwr attacks!
Round 12: The Big Wisniewski takes 4 damage.
Round 12: You lose 1 hit point
Round 12: You lose 20 hit points
Round 12: eventvwr attacks!
Round 13: You lose 1 hit point
Round 13: You lose 1 hit point
Round 13: You lose 18 hit points
Round 13: eventvwr attacks!
Round 14: The Big Wisniewski takes 3 damage.
Round 14: Polyfella lodges the ice-cold pick in your enemy, dealing 24 damage.
Round 14: The Big Wisniewski takes 24 damage.
Round 14: You lose 1 hit point
Round 14: You lose 19 hit points
Uh oh, I'm having trouble in combat.
Round 14: eventvwr casts SAUCESTORM!
Round 15: The Big Wisniewski takes 106 damage.
Round 15: The Big Wisniewski takes 106 damage.
Round 15: You lose 1 hit point
Round 15: You lose 11 hit points
Hmmm, I don't really know what to do in this combat but it looks like I'll live.
Round 15: eventvwr casts SAUCESTORM!
Round 16: The Big Wisniewski takes 106 damage.
Round 16: The Big Wisniewski takes 53 damage.
Round 16: You lose 1 hit point
Round 16: You lose 19 hit points
Hmmm, I don't really know what to do in this combat but it looks like I'll live.
Round 16: eventvwr casts SAUCESTORM!
Round 17: The Big Wisniewski takes 106 damage.
Round 17: The Big Wisniewski takes 53 damage.
Round 17: You lose 1 hit point
Hmmm, I don't really know what to do in this combat but it looks like I'll live.
Round 17: eventvwr casts SAUCESTORM!
Round 18: The Big Wisniewski takes 106 damage.
Round 18: The Big Wisniewski takes 53 damage.
Round 18: Polyfella lodges the ice-cold pick in your enemy, dealing 22 damage.
Round 18: The Big Wisniewski takes 22 damage.
Round 18: You lose 1 hit point
Round 18: You lose 18 hit points
Could not handle monster, sorry
Round 18: eventvwr executes a macro!
KoLmafia thinks it is round 19 but KoL thinks it is round 18
You're on your own, partner.
Click here to continue in the relay browser.

>Round 18: eventvwr uses the gas can and uses the filthy poultice!
Round 19: The Big Wisniewski takes 602 damage.
Round 19: You gain 80 hit points
Round 19: The Big Wisniewski takes 482 damage.
Round 19: You lose 1 hit point
Round 19: eventvwr casts SAUCESTORM!
Round 20: The Big Wisniewski takes 106 damage.
Round 20: The Big Wisniewski takes 53 damage.
Round 20: The Big Wisniewski takes 289 damage.
Round 20: You lose 1 hit point
Round 20: eventvwr wins the fight!
After Battle: Polyfella dislodges some Meat from the ground with the pick.
You gain 54 Meat
After Battle: Polyfella hops around, dancing a jig accompanied by wet squelching noises.
You acquire an item: solid gold bowling ball
After Battle: You gain 66 Fortitude
After Battle: You gain 61 Magicalness
After Battle: You gain 158 Roguishness
You gain a Moxie point!
War finished: hippies defeated

> sl_ascend

>Thank you for using sl_ascend!
If you need to configure the script, choose soolascend from the drop-down "run script" menu in your browser.
If you want to contribute, please open an issue at on Github
Hello eventvwr, time to explode!
This is version: 295 Mafia: 19141
This is day 5.
Turns played: 808 current adventures: 43
Current Ascension: Standard
CCS set to null
Found completed Island War (12)
Putting on reinforced beaded headband...
Equipment changed.
Putting on glowing red eye...
Equipment changed.
Turn(808): Starting with 43 left at Level: 13
Encounter: -10.0 Exp Bonus: 9.537280701754387
Meat Drop: 230.0 Item Drop: 295.87482193696064
HP: 114/324, MP: 31/185
Tummy: 0/15 Liver: 0/15 Spleen: 0/15
ML: 10 control: 0
Delay between adventures... beep boop... 
Countdown: 1 second...
Waiting completed.
Encounter: Choose a Soundtrack
Setting soundtrack to Food Vibrations
Change successful to Food VibrationsWe have 10 SongBoom BoomBoxen songens left!
Some sidequest is not done for some raisin. Some sidequest is missing, or something is missing, or something is not not something. We don't know what to do.

### PR DESCRIPTION
**Pull request by MatthewDarling**
Resolves #166. Insofar as the manual fix is done automatically now, anyway.

Do we want to hold off on merging until verifying the fix live?

### CODE REVIEW

**Comment by soolar** [comment]
Yep, I'd like the fix verified first, even if this does seem like this couldn't be anything worse than harmless in the worst case scenario. Might as well verify it first.

**Comment by MatthewDarling** [comment]
Sounds good, initially I wasn't sure how I would actually test it. Just realized that as long as I manually kill the last boss of the war, it should get stuck and then I can try the new code to get unstuck.

**Comment by MatthewDarling** [comment]
I don't get an infinite loop as originally reported, but with `master` and killing the war boss manually, I get:

```
You're not at war.
Turn(675): Starting with 116 left at Level: 14
...
You're not at war.
Some sidequest is not done for some raisin. Some sidequest is missing, or something is missing, or something is not not something. We don't know what to do.
```

And... this branch doesn't actually fix it. Good thing you didn't merge on faith :) It seems like it's able to detect that the war is over, because `sl_war == "finished"`. However, it's not moving to `"done"`, and `sl_prewar` is still `"started"`. So I guess `council()` doesn't help in DG, maybe because of the changed quest text.

It's possible that `council()` would fix the problem in other paths, not sure though.

The "you're not at war" messages are actually both from [`bat_consumption()`, when it tries to sell for quarters/dimes](https://github.com/soolar/sl_ascend/blob/master/RELEASE/scripts/sl_ascend/sl_batpath.ash#L372). Failing to do that breaks the rest of `bat_consumption()`. So I'll try to deal with the error there, seems reasonable just to continue if we fail to sell.

Still investigating what needs to be done to actually detect the finished quest.

**Comment by MatthewDarling** [comment]
Just noticed that "finished" is actually after "done". Semantics are hard. So I reset it to `"done"`, ran with this branch, and that did fix things 👍 False alarm!

Anyway, `is_accessible($coinmaster[Quartermaster])`/`Dimemaster` fixed the selling problem.

**Pull request merged**
